name = "XLSXrw"
uuid = "1fd09be0-6fc5-4b87-a210-c704f03ef69b"
authors = ["Christian Kral <dr.christian.kral@gmail.com>"]
version = "0.1.0"

[deps]
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
julia = "^1.0.0"
