name = "WorkflowXLSX"
uuid = "2a1aca37-82bb-4c5b-939f-ac9d327f2328"
authors = ["Christian Kral <dr.christian.kral@gmail.com>"]
version = "0.1.1"

[deps]
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ElectricalEngineering = "84e62fa8-74a0-5990-9214-c45bd74ae4d7"

[compat]
julia = "1"
XLSX = "0.8.4, 1"
Unitful = "1.12.0, 1"
ElectricalEngineering = "0.6.2, 1"
