name = "WorkflowXLSX"
uuid = "2a1aca37-82bb-4c5b-939f-ac9d327f2328"
authors = ["Christian Kral <dr.christian.kral@gmail.com>"]
version = "0.1.0"

[deps]
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
julia = "^1.0.0"
XLSX = "^0.8.4"
